<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>..\..\..\Autodesk\Revit 2025\RevitAPI.dll</HintPath>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>..\..\..\Autodesk\Revit 2025\RevitAPIUI.dll</HintPath>
    </Reference>
    <Reference Include="RevitUIAPI">
      <HintPath>..\..\..\Autodesk\Revit 2025\RevitUIAPI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
    <Folder Include="Models\" />
    <Folder Include="ViewModels\" />
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="echo ===== POST BUILD =====&#xD;&#xA;&#xD;&#xA;echo TargetPath:&#xD;&#xA;echo $(TargetPath)&#xD;&#xA;&#xD;&#xA;set ADDIN_DIR=C:\ProgramData\Autodesk\Revit\Addins\2025\DALTUDTXD&#xD;&#xA;&#xD;&#xA;if not exist &quot;%25ADDIN_DIR%25&quot; mkdir &quot;%25ADDIN_DIR%25&quot;&#xD;&#xA;&#xD;&#xA;echo Copy DLL...&#xD;&#xA;copy &quot;$(TargetPath)&quot; &quot;%25ADDIN_DIR%25&quot; /Y&#xD;&#xA;&#xD;&#xA;echo Copy ADDIN...&#xD;&#xA;copy &quot;$(ProjectDir)DALTUDTXD_AddinTinhLienKet_0315168_68th3.addin&quot; &quot;C:\ProgramData\Autodesk\Revit\Addins\2025\&quot; /Y&#xD;&#xA;&#xD;&#xA;echo Copy Assets...&#xD;&#xA;xcopy &quot;$(ProjectDir)Assets&quot; &quot;%25ADDIN_DIR%25\Assets&quot; /E /I /Y&#xD;&#xA;&#xD;&#xA;echo ===== DONE =====&#xD;&#xA;pause&#xD;&#xA;" />
  </Target>

</Project>
